title: "Felipe Labra Irribarra"
author: "Felipe Labra Irribarra"
description: "Pontificia Universidad Católica de Chile"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", sidebaricon: home}
  - {file: "aboutme.md", sidebaricon: address-card}
  - {title: "CV", file: "/FLI.pdf", icon: home}

  - title: "Seminars"
    sidebaricon: "calendar"
    children:
      - {title: "Seminar 1", file: "seminar1.md"}
      - {title: "Seminar 2", file: "seminar2.md"}
      - {title: "Seminar 3", file: "seminar3.md"}


external:                       # accepts {file, title, url, icon, sidebaricon}
 # - {title: Mail, icon: envelope, url: "mailto:author@example.com"}
 # - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
 # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
